channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=24.0
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - tensorflow-macos==2.13.1
  - tensorflow==2.13.1
name: mlflow-env
